version: "3.9"

services:
  mcp-server:
    build: .
    container_name: mcp-server
    depends_on:
      - postgres
      - redis
      - sqlserver
    env_file:
      - .env
    environment:
      # Basic config overrides
      POSTGRES_DSN: postgresql://mcp_user:mcp_pass@postgres:5432/mcp_meta
      REDIS_URL: redis://redis:6379/0
      SQLSERVER_DSN: Driver={ODBC Driver 18 for SQL Server};Server=sqlserver,1433;Database=master;Uid=sa;Pwd=YourStrong!Passw0rd;Encrypt=no
      APP_ENV: development
      LOG_LEVEL: info
      PYTHONPATH: /app/src
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./sql:/app/sql
    restart: on-failure

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_pass
      POSTGRES_DB: mcp_meta
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mcp_user", "-d", "mcp_meta"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./sql:/sql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT 1" -C
      interval: 20s
      retries: 10

volumes:
  pgdata:
  redisdata:
  sqlserverdata: